stages:
- stage: code_quality
  displayName: Static analysis
  jobs:
  - job: flake8
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'

    - script: pip install flake8
      displayName: Install dependencies

    - script: flake8
      displayName: Run flake8

- stage: run_test_suite
  displayName: Run the test suite
  jobs:
  - job: test
    strategy:
      matrix:
        Linux-Py35:
          imageName: 'ubuntu-16.04'
          python.version: '3.5'
        Linux-Py38:
          imageName: 'ubuntu-latest'
          python.version: '3.8'
        Linux-PyPy3:
          imageName: 'ubuntu-latest'
          python.version: 'pypy3'
        Mac-Py35:
          imageName: 'macos-10.13'
          python.version: '3.5'
        Mac-Py38:
          imageName: 'macos-latest'
          python.version: '3.8'
        Win-Py35:
          imageName: 'vs2017-win2016'
          python.version: '3.5'
        Win-Py38:
          imageName: 'windows-latest'
          python.version: '3.8'

    pool:
      vmImage: '$(imageName)'

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'

    - script: pip install .[test]
      displayName: Install dependencies

    - script: coverage run pytest --junit-xml=junit.xml
      displayName: Run pytest

    - task: PublishTestResults@2
      displayName: Publish test results
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: '$(System.DefaultWorkingDirectory)/junit.xml'

    - script: coverage xml
      displayName: Generate coverage report

    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage.xml'
